Repository googleapis/java-notification, pull requests merged in 2020-12, with the labels that each got.

#201 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#202 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#203 chore(deps): bundle storage dep updates to avoid conflicts
  renovate.json
  synth.py
Labels: automerge, cla: yes

#207 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#216 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#220 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#221 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full, merge
