Repository googleapis/java-notification, pull requests merged in 2020-09, with the labels that each got.

#122 build(ci): enable auto-release for dependency-update-only releases
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: cla: yes, context: full

#123 chore(java): set yoshi-java as default CODEOWNER
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#77 chore: add client_documentation link
  .repo-metadata.json
Labels: cla: yes

#138 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#137 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes

#143 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
