Repository googleapis/java-notification, pull requests merged in 2021-09, with the labels that each got.

#405 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: storage, automerge

#398 ci: removing linkage-monitor from the required checks
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: storage, context: full

#411 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, api: storage, automerge

#413 chore(java): install maven 3.8.1 at runtime
  .github/trusted-contribution.yml
  .github/workflows/ci.yaml
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
  synth.metadata
Labels: cla: yes, api: storage, context: partial

#414 ci: removing linkage-monitor from required checks
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: storage

#426 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, api: storage

#441 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: storage, automerge

#443 chore: change branch master to main in github configurations
  README.md
Labels: cla: yes, api: storage, automerge
